app = 'discord-esjwfw'
primary_region = 'fra'

[build]

[processes]
  app = 'python main.py'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  # ئەگەر هێلت چێکی هەیە لێرە دەتوانرێت لاببرێت یان پڕۆسەکە تەنها وەک background process دابنرێت
