app = 'discord-esjwfw'
primary_region = 'fra'

[build]

[processes]
  app = 'python main.py'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200
